
spring:
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2
  datasource:
    url: jdbc:mysql://database-1.ca00k3yenfz9.ap-northeast-2.rds.amazonaws.com:13306/stackpre34?useUnicode=yes&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: ${STACKPRE34_ID}
    password: ${STACKPRE34_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Fetch size 설정 1+N 문제 임시 해결
        default_batch_fetch_size: 1000
        # Entity에 예약어가 있다면 '' 자동 추가
  #        auto_quote_keyword: true
  sql:
    init:
      mode: always

# 디버깅 용이하게 하기 위한 로깅 레벨 수정
logging.level:
  org.hibernate.SQL: debug
  org:
    hibernate:
      type:
        descriptor:
          sql:
            org.hibernate.type.descriptor.sql.BasicBinder: trace
    springframework:
      web.servlet: debug